name: proloco_piazzola
description: App Flutter per la gestione degli espositori di ProLoco Piazzola
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  file_picker: ^10.2.0
  csv: ^6.0.0
  flutter_hooks: ^0.21.2

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/piazzola_sul_brenta-stemma.png"
